[package]
name = "wiki"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7",features = ["blocking"]}
crossterm = "0.26.1"
serde = {version = "1.0.209",features = ["serde_derive"]}
serde_json = "1.0.127"